name: Build Blutter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'worawit/blutter'
    
    - name: Install dependencies
      run: |
        brew update
        brew install cmake ninja pkg-config icu4c capstone
        brew tap dart-lang/dart
        brew install dart
        python3 -m venv venv
        source venv/bin/activate
        pip install pyelftools requests
    
    - name: Build
      run: |
        source venv/bin/activate
        cd blutter
        DARTLIB=$(brew --prefix dart)/libexec
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DDARTLIB=$DARTLIB
        make -j$(sysctl -n hw.ncpu)
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: blutter
        path: |
          ./blutter/build/blutter
          ./blutter/build/*.dylib
          ./blutter/blutter.py
          ./blutter/*.py
        retention-days: 7
